### ISSUE TITLE
Ability to pause/resume sending logs on demand

### ISSUE THREAD

**Issue by gr0** [sematext/sematext-logsene-ios#13]
There may be a need to pause/resume sending logs on demand. This issue is created to discussion and progress on providing such functionality.

**Comment by otisg** [comment]
I assume the behaviour would be much like or exactly like when a device is disconnected from the network?

**Comment by gr0** [comment]
Yes, that is my initial thinking.

**Comment by gr0** [comment]
The ability to pause sending logs is now available with version 1.3.5 - the commit that addresses this is: https://github.com/sematext/sematext-logsene-ios/commit/ec99bfb317a11419a2892edd29ef4d25e0e8467c.

The new library version was also released.
