### ISSUE TITLE
Update SDK to Xcode 12 and Swift 5.3

### ISSUE THREAD

**Issue by gr0** [sematext/sematext-logsene-ios#18]
Now that iOS 14 is available, the updated Xcode and Swift were released. We should update our iOS SDK to match the new version.

**Comment by philmitchell** [comment]
What's the status of this? I suspect your dependency on `SQLite.swift` is going to be a problem. Even on iOS 13 it caused headaches because of [conflicts with other sqlites](https://forums.swift.org/t/grdb-sqlcipher-crash-release-builds-only-solved/37598).

`sematext-logsene-ios` has prevented me from updating my app to iOS 14. I love the sematexst service, but at this point, I'm planning to rewrite `SqliteObjectBuffer` to use my own persistent store.

**Comment by otisg** [comment]
@philmitchell this is in our next sprint, so will be done in the next ~2 weeks.

**Comment by philmitchell** [comment]
Thanks for the update @otisg

**Comment by gr0** [comment]
Hi @philmitchell :) As far as the `SQLLite.swift` - we know that it was not updated for quite some time and we have to find a replacement for it. I'm strongly considering [GRDB.swift](https://github.com/groue/GRDB.swift) as the library of choice.

**Comment by philmitchell** [comment]
Hi @gr0! GRDB is fantastic, but a pretty heavy dependency. I use GRDB/SQLCipher in my project, not sure how that will play with the GRDB that you might import.

**Comment by otisg** [comment]
Thanks for this info, @philmitchell .  In your own projects have you considered and evaluated any alternatives?

**Comment by gr0** [comment]
Thanks @philmitchell, that's a very valuable input. I also thought about [FMDB](https://github.com/ccgus/fmdb), so this is yet another alternative that we could use.

**Comment by philmitchell** [comment]
To be honest, I would like to see you find a solution that doesn't require a third-party sqlite library. FMDB is fine (it's older, stable, not under such active development as GRDB), but I don't want to add either dependency to my app just for sematext. Have you considered using CoreData? Or a flat file? I wonder how other loggers handle this problem?

**Comment by gr0** [comment]
I'll discuss the options internally. It seems that having a flat file or using CoreData may be a good idea.

**Comment by gr0** [comment]
HI @philmitchell - we just released version `1.6.0`. It doesn't contain the `SQLite.swift` as we've rewritten the SQLite support. It doesn't require any kind of external dependencies now. If you could test it and let us know what you think it would be awesome.

**Comment by philmitchell** [comment]
Hi @gr0 thanks for the heads up! Unfortunately, I tried to integrate `1.6.0` and get a ton of redefinition errors such as: `redefinition of 'sqlite3_file'`, `redefinition of 'sqlite3_io_methods'`, etc.

I am using GRDB w/ SQLCipher and SQLCipher needs to have its own version of sqlite. So even though you're using the built-in version, I don't see a way to make this work. Do you?

**Comment by gr0** [comment]
Thanks for getting back to us @philmitchell. Indeed things may be clashing here. Give me a few, I'll discuss that internally and get back to you. Maybe together we can find a resolution to such problem. I would really like to avoid re-inventing the wheel and re-write the persistent buffer, but maybe that wouldn't be that bad after all.

**Comment by gr0** [comment]
I think I have an idea @philmitchell, but I'm not sure if I'll be able to work on it and test it this week. I'll try to work on it on Tuesday/Friday, but can't promise. I'll get back to you as soon as I have any kind of information. That should be next week.

**Comment by gr0** [comment]
Hi @philmitchell, I've looked through the code and it seems the only way I can force CQLCipher and Sematext iOS Mobile Logs SDK working together is by incorporating compatibility with SQLCipher to our lib. I will dig more and will see if there are other workarounds. If not, maybe adding SQLCipher wouldn't be that bad ;)

**Comment by gr0** [comment]
It seems that we will be removing the need for `SQLite` headers from the iOS Mobile SDK. I created a branch that I'm working on https://github.com/sematext/sematext-logsene-ios/tree/use_files_as_persistent_log_storage and I'm going to develop that in the next days. The `1.7.0` release will be using pure files approach, just like majority of the log shippers.

**Comment by philmitchell** [comment]
That's great news, thanks for the update @gr0.

**Comment by gr0** [comment]
No problem, I'll reach out once I'm done :)

**Comment by gr0** [comment]
@philmitchell version 1.7.0 was released - https://github.com/sematext/sematext-logsene-ios/releases/tag/1.7.0, it no longer needs SQLite 3, so there shouldn't be a clash with the SQLCipher :)

**Comment by philmitchell** [comment]
Thank you @gr0 ... Awesome! I have it installed and working.

**Comment by gr0** [comment]
Great :)
