### ISSUE TITLE
Swift 4 version of the pod

### ISSUE THREAD

**Issue by jprossardalia** [sematext/sematext-logsene-ios#3]
Hello  is there any plan to release the swift 4 version of this repo. The current repo does not work with xCode 9

**Comment by otisg** [comment]
+1 for that, @jprossardalia.  Do you have a sense of how big the changes are and are you planning on submitting a PR (I see you forked the repo)?

**Comment by jprossardalia** [comment]
I actually forked it get the commit done by  @aebischers for the swift 3 migration. It got build without any problem but I'm still not able to get the logs on the dashboard.

**Comment by otisg** [comment]
@jprossardalia & @aebischers are there any errors you are seeing anywhere, anything that would help us trace this?

**Comment by shgew** [comment]
Any updates on this issue? The project is still not buildable on newer Xcode versions.

**Comment by amir-hadzic** [comment]
@Gamedar we will look into this and have a fix in the next two weeks.

**Comment by shgew** [comment]
Thanks!

**Comment by gr0** [comment]
@Gamedar we have a branch with newest Xcode support - https://github.com/sematext/sematext-logsene-ios/tree/xcode_11_support. Have a look if you want ;)

**Comment by shgew** [comment]
> @Gamedar we have a branch with newest Xcode support - https://github.com/sematext/sematext-logsene-ios/tree/xcode_11_support. Have a look if you want ;)

Will do! Thank you for your work :)

**Comment by gr0** [comment]
Changes went into master branch, new version of the pod was released. Travis says that the build now passes using the latest Xcode. Let us know if you will finds more issues :)
