### ISSUE TITLE
Swift 4 migration

### ISSUE THREAD

**Issue by shgew** [sematext/sematext-logsene-ios#6]
There is a dependency listed in the .podspec file: `s.dependency 'SQLite.swift', '~> 0.10.1'`.
However, the version listed only supports Swift 3, as a result, the project can't be built with Xcode 11.
Are you planning to migrate this repo to a newer Swift version?

**Comment by amir-hadzic** [comment]
Hey, thanks for bringing this up. Let's track this in the existing issue #3.

**Comment by shgew** [comment]
Sure
