### ISSUE TITLE
SQLite.swift dependency has hard-coded path

### ISSUE THREAD

**Issue by philmitchell** [sematext/sematext-logsene-ios#7]
This is a known _wontfix_ issue: https://github.com/stephencelis/SQLite.swift/issues/425

The hard-coded path causes compilation problems such as duplicate `modulemap` files (if you have _Xcode.app_ in your path, and missing files if you don't. (Assuming you're using something other than _Xcode.app_, which many devs would be.)

[UPDATED] Xcode 11.4.1, Swift 5.2

**Comment by otisg** [comment]
Btw. @philmitchell which version of Xcode/Swift are you using?

**Comment by gr0** [comment]
@philmitchell I have a working branch of the library which works with the newest version of Xcode - https://github.com/sematext/sematext-logsene-ios/tree/xcode_11_support, give it a try if you want :)

**Comment by philmitchell** [comment]
Thanks @gr0 ... it's working for me. Fyi, had to add `import UIKit` to _Core.swift_ and add _SQLite.swift_ using SPM.

**Comment by gr0** [comment]
Awesome @philmitchell, thanks for the input on this! I'll be modifying the code tomorrow as well adding the changes :)

**Comment by gr0** [comment]
The change went to master and version 1.1.0 of the pod was released :) Let us know if you will find any more issues!

**Comment by philmitchell** [comment]
Thanks @gr0, but due to the issues with the _SQLite.swift_ cocoapod, it does not work for me. It only works if I can install _SQLite.swift_ via SPM. Do you plan to add a package manifest to enable SPM installation?

**Comment by gr0** [comment]
Sure, I will add an issue to myself. I will try to find time to work on that and add support for Swift package manager in the next few days.

**Comment by gr0** [comment]
@philmitchell I've created a new PR - https://github.com/sematext/sematext-logsene-ios/pull/11, would you be willing to take a look at it and see if that works for you? I can see that the **swift package describe** works:

```
Name: Logsene
Path: ...
Modules:
    Name: Logsene
    C99name: Logsene
    Type: library
    Module type: SwiftTarget
    Path: ...
    Sources: Core.swift, DispatchQueue+Once.swift, LReachability.swift, LogseneClient.swift, NSDate.swift, NSLogIntercept.swift, SqliteObjectBuffer.swift, String.swift, Worker.swift

    Name: Example
    C99name: Example
    Type: test
    Module type: SwiftTarget
    Path: ...
    Sources: AppDelegate.swift, Logger.swift, TestActionsController.swift, ViewController.swift
```

The dependencies are also correctly resolved:
```
.
└── SQLite.swift<https://github.com/stephencelis/SQLite.swift.git@0.12.2>
```

I'm not sure though if I haven't forgot about something. I didn't work much with Swift Package Manager, so I could ;)
